/* eslint-disable react/no-string-refs */
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import dp from '../../public/images/profile/final2.png'
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow, MailTo } from '@/components/icons';
import HireMe from '@/components/HireMe';
import ContactMe from '@/components/ContactMe';
import Modal from '@mui/material/Modal';
import * as React from 'react';
import spaceMan from '../../public/images/svgs/space_boy.svg'


export default function Home() {
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-black bg-light w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='w-full flex'>
            <div className='flex items-center justify-between w-full '>
              <Image src={dp} alt='Prasad Boye' className='w-21 h-auto' />
            </div>
            <div className='w-3/4 text-justify'>
              <AnimatedText text={'Turning Vision Into Reality With Code And Design'}/>
              <p className="my-4 text-base font-medium text-justify">
                Hey there, I am <strong>Prasad Boye</strong> a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              {/* <ReactTyped
                strings={["Hey there, I am <strong>Prasad Boye</strong> a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. Explore my latest projects and articles, showcasing my expertise in React.js and web development."]} typeSpeed={40} /> */}
              <div className="flex items-center self-start mt-2">
                <Link href="./dummy.pdf" target="_blank" 
                className="flex items-center bg-dark text-light p-2.5 px-6 
                rounded-lg text-lg font-semibold border-2 border-solid border-transparent
                hover:bg-light hover:text-dark hover:border-dark"
                download={true}>
                  Resume <LinkArrow className={"w-6 ml-2"}/>
                  </Link>
                <>
                  <button onClick={handleOpen}
                  className="flex items-center bg-dark text-light p-2.5 px-6 
                  rounded-lg text-lg font-semibold border-2 border-solid border-transparent
                  hover:bg-light hover:text-dark hover:border-dark ml-3
                  fill-white hover:fill-dark"
                  >
                    Contact <MailTo className={"w-6 ml-2 mt-1"}/>
                  </button>
                  <Modal
                    sx={{display: 'flex', 
                    alignItems: 'center',
                    justifyContent: 'center',
                    right: '35%',
                    top: '25%',
                    bottom: '25%',
                    left: '25%',
                  }}
                    open={open}
                    onClose={handleClose}
                    aria-labelledby="modal-modal-title"
                    aria-describedby="modal-modal-description"
                  >
                      <ContactMe handleClose={handleClose}/>
                  </Modal>
                </>
              </div>                
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className='w-60 absolute right-8 bottom-8 inline-block'>
          <Image alt='Prasad Boye' src={spaceMan} className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
