import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import dp from '../../public/images/profile/final2.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-black bg-light w-full min-h-screen'>
        <Layout>
          <div className='flex items-center justify-between w-full'>
            <Image src={dp} alt='Prasad Boye' className='w-21 h-auto' />
          </div>
        </Layout>
      </main>
    </>
  )
}
